# Generated by Django 4.2.13 on 2024-12-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240225_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('Sanaa', 'Sanaa'), ('Aden', 'Aden'), ('Tize', 'Tize')], max_length=100)),
                ('country', models.CharField(choices=[('Yemen', 'Yemen')], max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/supplier_images/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.suppliercategory')),
            ],
        ),
    ]
