# Generated by Django 4.2.13 on 2024-12-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cart_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='supplier',
        ),
    ]
