# Generated by Django 4.2.13 on 2024-12-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_cartitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
            preserve_default=False,
        ),
    ]
