# Generated by Django 5.2.5 on 2025-09-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ManyToManyField(to='core.suppliercategory'),
        ),
    ]
