# Generated by Django 5.2.4 on 2025-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_supplier_category_supplier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/supplier_category_images/'),
        ),
    ]
