# Generated by Django 5.2.4 on 2025-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_suppliercategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('out_for_delivey', 'Out for Delivery')], default='Pending', max_length=50),
        ),
    ]
