# Generated by Django 5.1.7 on 2025-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_supplier_primary_color_supplier_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='panal_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/supplier_images/'),
        ),
    ]
