# Generated by Django 5.1.7 on 2025-12-28 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_supplier_panal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppierads',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ads', to='core.product'),
        ),
    ]
