# Generated by Django 5.1.7 on 2025-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_suppierads_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='accent_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='footer_color',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='navbar_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='text_color',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='secondary_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
