# Generated by Django 5.1.7 on 2025-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_supplier_accent_color_supplier_footer_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='SAR', max_length=10),
        ),
    ]
