# Generated by Django 5.1.7 on 2025-12-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='store_id',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
