# Generated by Django 5.1.7 on 2025-12-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_orderstatus_orderworkflow_order_pipeline_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
