# Generated by Django 5.1.7 on 2025-12-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_orderpaymentreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='requires_payment',
            field=models.BooleanField(default=False, verbose_name='يتطلب سداد كامل'),
        ),
    ]
