# Generated by Django 5.1.7 on 2025-12-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_supplier_latitude_supplier_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery_fee_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='نسبة رسوم التوصيل لكل كم'),
        ),
    ]
