# Generated by Django 5.1.7 on 2025-12-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_supplier_delivery_fee_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='enable_delivery_fees',
            field=models.BooleanField(default=False, verbose_name='تفعيل رسوم التوصيل'),
        ),
    ]
