# Generated by Django 5.1.7 on 2026-01-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_supplier_enable_delivery_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='show_order_amounts',
            field=models.BooleanField(default=True, verbose_name='عرض مبالغ الطلبات'),
        ),
    ]
