# Generated by Django 5.1.7 on 2026-01-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_supplier_show_order_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOfferAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_offers', to='core.product')),
            ],
        ),
    ]
