# Generated by Django 5.1.7 on 2026-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_platformofferad'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategory',
            name='producing_family',
            field=models.BooleanField(default=False),
        ),
    ]
