# Generated by Django 5.1.7 on 2026-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_suppliercategory_producing_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='show_platform_ads',
            field=models.BooleanField(default=True, verbose_name='عرض إعلانات المنصة'),
        ),
    ]
