# Generated by Django 5.1.7 on 2026-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_supplier_show_platform_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='متجرك الإلكتروني', max_length=100, verbose_name='اسم الموقع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='الشعار')),
                ('description', models.TextField(default='منصة متكاملة توفر لك تجربة تسوق فريدة ومميزة.', verbose_name='وصف الموقع')),
                ('customer_service_number', models.CharField(default='+966 50 123 4567', max_length=20, verbose_name='رقم خدمة العملاء (موبايل)')),
                ('company_email', models.EmailField(default='support@store.com', max_length=254, verbose_name='البريد الإلكتروني للشركة')),
                ('company_landline', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الأرضي')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط انستقرام')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب للدعم')),
                ('show_download_app', models.BooleanField(default=True, verbose_name='عرض روابط تحميل التطبيق')),
                ('app_store_link', models.URLField(blank=True, verbose_name='رابط App Store')),
                ('google_play_link', models.URLField(blank=True, verbose_name='رابط Google Play')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
