# Generated by Django 5.1.7 on 2026-01-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='الأولوية (الأعلى يظهر أولاً)'),
        ),
    ]
