# Generated by Django 5.1.7 on 2026-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_supplier_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='laoder_image',
            field=models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='صورة التحميل'),
        ),
    ]
