# Generated by Django 5.1.7 on 2026-01-06 19:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_systemsettings_laoder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_to_path),
        ),
        migrations.AlterField(
            model_name='suppierads',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_to_path),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='panal_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_path),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_path),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_path),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='laoder_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_path, verbose_name='صورة التحميل'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_path, verbose_name='الشعار'),
        ),
    ]
