# Generated by Django 5.2.8 on 2026-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_product_image_alter_suppierads_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النشاط التجاري')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم صاحب النشاط')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('business_type', models.CharField(max_length=100, verbose_name='نوع النشاط')),
                ('message', models.TextField(blank=True, null=True, verbose_name='رسالة إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
            ],
            options={
                'verbose_name': 'طلب انضمام نشاط تجاري',
                'verbose_name_plural': 'طلبات انضمام الأنشطة التجارية',
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='accent_color',
            field=models.CharField(default='#9abfc4', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='footer_color',
            field=models.CharField(default='#3a505e', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='navbar_color',
            field=models.CharField(default='#ef7d2d', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='primary_color',
            field=models.CharField(default='#ef7d2d', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='text_color',
            field=models.CharField(default='#3a505e', max_length=7),
        ),
    ]
