# Generated by Django 5.2.8 on 2026-01-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_businessrequest_alter_supplier_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف لمحركات البحث (SEO Description)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='الكلمات المفتاحية (SEO Keywords)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان لمحركات البحث (SEO Title)'),
        ),
    ]
