# Generated by Django 5.1.7 on 2026-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='الكود API واتساب'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, verbose_name='رابط API واتساب'),
        ),
    ]
