# Generated by Django 6.0.1 on 2026-01-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsettings_whatsapp_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='supplier',
        ),
    ]
