# Generated by Django 6.0.1 on 2026-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_category_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='can_add_categories',
            field=models.BooleanField(default=False, verbose_name='إضافة فئات'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='can_add_product_categories',
            field=models.BooleanField(default=False, verbose_name='إضافة فئات المنتجات'),
        ),
    ]
