# Generated by Django 5.1.7 on 2026-01-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_supplier_can_add_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformofferad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
