# Generated by Django 6.0.1 on 2026-01-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_product_video_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العملة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز العملة (ISO)')),
                ('symbol', models.CharField(max_length=10, verbose_name='الرمز (الشعار)')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency'),
        ),
    ]
