# Generated by Django 6.0.1 on 2026-01-13 14:08

from django.db import migrations

def migrate_currency(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    Supplier = apps.get_model('core', 'Supplier')

    # Create default currencies
    sar, _ = Currency.objects.get_or_create(name='Saudi Riyal', code='SAR', symbol='ر.س')
    yer, _ = Currency.objects.get_or_create(name='Yemeni Rial', code='YER', symbol='ر.ي')

    # Map existing data
    for supplier in Supplier.objects.all():
        if supplier.currency == 'ر.س':
            supplier.currency_new = sar
        elif supplier.currency == 'ر.ي' or supplier.currency == 'YER':
            supplier.currency_new = yer
        else:
            # Default to SAR if unknown but has value
            supplier.currency_new = sar
        supplier.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_currency_supplier_currency_new'),
    ]

    operations = [
        migrations.RunPython(migrate_currency),
    ]
