# Generated by Django 6.0.1 on 2026-01-13 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_swap_currency_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuppierAds',
            new_name='SupplierAds',
        ),
    ]
