# Generated by Django 6.0.1 on 2026-01-19 15:05

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_supplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAdPlatfrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.upload_to_path)),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
    ]
