# Generated by Django 6.0.1 on 2026-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_supplieradplatfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieradplatfrom',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
