# Generated by Django 6.0.1 on 2026-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_supplieradplatfrom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='show_system_logo',
            field=models.BooleanField(default=True, verbose_name='عرض شعار المنصة في الشريط العلوي'),
        ),
    ]
