# Generated by Django 6.0.1 on 2026-01-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_supplier_show_system_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieradplatfrom',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
    ]
