# Generated by Django 6.0.1 on 2026-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_supplieradplatfrom_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieradplatfrom',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
