# Generated by Django 6.0.1 on 2026-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_supplieradplatfrom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieradplatfrom',
            name='tag_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نص الشارة'),
        ),
    ]
