# Generated by Django 6.0.1 on 2026-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_supplieradplatfrom_tag_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='can_add_products',
            field=models.BooleanField(default=False, verbose_name='إضافة منتجات'),
        ),
    ]
