# Generated by Django 6.0.1 on 2026-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_supplier_can_add_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieradplatfrom',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الانتهاء'),
        ),
        migrations.AddField(
            model_name='supplieradplatfrom',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت البدء'),
        ),
    ]
