# Generated by Django 6.0.1 on 2026-01-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_supplieradplatfrom_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stock_decreased',
            field=models.BooleanField(default=False, verbose_name='تم تقليل المخزون'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='المخزون'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='decrease_stock',
            field=models.BooleanField(default=False, verbose_name='تقليل المخزون'),
        ),
    ]
