# Generated by Django 6.0.1 on 2026-01-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_order_is_stock_decreased_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='return_policy',
            field=models.TextField(blank=True, null=True, verbose_name='سياسة الاستبدال والاسترجاع'),
        ),
    ]
