# Generated by Django 6.0.1 on 2026-01-31 20:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_supplier_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieradplatfrom',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_path, verbose_name='صورة الجوال (Mobile)'),
        ),
        migrations.AlterField(
            model_name='supplieradplatfrom',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_to_path, verbose_name='صورة سطح المكتب (Desktop)'),
        ),
    ]
