# Generated by Django 6.0.1 on 2026-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_supplieradplatfrom_mobile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='show_out_of_stock',
            field=models.BooleanField(default=True, verbose_name='عرض المنتجات غير المتوفرة'),
        ),
    ]
