# Generated by Django 6.0.1 on 2026-01-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_supplier_show_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='الموافقة على الشروط والأحكام'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة على الشروط'),
        ),
    ]
