# Generated by Django 6.0.1 on 2026-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_order_cancellation_reason_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم هاتف إضافي'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='customer_service_number',
            field=models.CharField(default='+967 777 777 777', max_length=20, verbose_name='رقم خدمة العملاء (موبايل)'),
        ),
    ]
