# Generated by Django 6.0.1 on 2026-02-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='show_merchant_agreement',
            field=models.BooleanField(default=False, verbose_name='عرض اتفاقية التجار'),
        ),
    ]
