# Generated by Django 6.0.1 on 2026-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_systemsettings_show_merchant_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='accent_color',
            field=models.CharField(default='#00FFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='footer_color',
            field=models.CharField(default='#2B6CB0', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='navbar_color',
            field=models.CharField(default='#F58231', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='primary_color',
            field=models.CharField(default='#F58231', max_length=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='text_color',
            field=models.CharField(default='#4A5568', max_length=7),
        ),
    ]
