# Generated by Django 6.0.1 on 2026-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_supplier_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='has_seen_products_tour',
            field=models.BooleanField(default=False, verbose_name='شاهد جولة المنتجات'),
        ),
    ]
