# Generated by Django 6.0.1 on 2026-02-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_supplier_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='design_template',
            field=models.CharField(choices=[('default', 'Default Design'), ('modern_v2', 'Modern V2 Design')], default='default', max_length=20, verbose_name='تصميم المتجر'),
        ),
    ]
