# Generated by Django 6.0.1 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_add_has_seen_products_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', help_text='أدخل معرف بكسل ميتا (مثال: 1413008573165397)', max_length=50, verbose_name='معرف Meta Pixel'),
        ),
    ]
