# Generated by Django 6.0.1 on 2026-02-25 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_add_has_seen_products_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, help_text="مثال: 'mystore' → mystore.rawaaj.com", max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يحتوي النطاق الفرعي على أحرف صغيرة وأرقام وشُرَط فقط، ولا يبدأ أو ينتهي بشرطة.', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')], verbose_name='النطاق الفرعي'),
        ),
    ]
