# Generated by Django 6.0.1 on 2026-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_supplier_design_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='design_template',
            field=models.CharField(choices=[('default', 'Default Design'), ('modern_v2', 'Modern V2 Design'), ('luxury_dark', 'Luxury Dark Mode')], default='default', max_length=20, verbose_name='تصميم المتجر'),
        ),
    ]
