# Generated by Django 6.0.1 on 2026-02-25 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_meta_pixel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='الرابط')),
                ('page_type', models.CharField(choices=[('landing', 'الصفحة الرئيسية'), ('product_list', 'قائمة المنتجات'), ('product_detail', 'تفاصيل المنتج'), ('cart', 'سلة التسوق'), ('checkout', 'إتمام الشراء'), ('order_detail', 'تفاصيل الطلب'), ('join_business', 'انضمام تجاري'), ('profile', 'الملف الشخصي'), ('merchant_dashboard', 'لوحة التاجر'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='نوع الصفحة')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='نوع الطلب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='وكيل المستخدم')),
                ('device_type', models.CharField(choices=[('mobile', 'جوال'), ('tablet', 'تابلت'), ('desktop', 'حاسوب'), ('bot', 'روبوت'), ('unknown', 'غير معروف')], default='unknown', max_length=10, verbose_name='نوع الجهاز')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='المتصفح')),
                ('operating_system', models.CharField(blank=True, default='', max_length=100, verbose_name='نظام التشغيل')),
                ('referrer', models.URLField(blank=True, default='', max_length=2048, verbose_name='المرجع (Referrer)')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='معرف الجلسة')),
                ('response_status', models.PositiveSmallIntegerField(default=200, verbose_name='حالة الاستجابة')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الزيارة')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_statistics', to='core.supplier', verbose_name='المتجر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_statistics', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إحصائية زيارة',
                'verbose_name_plural': 'إحصائيات الموقع',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='core_websit_visited_27d901_idx'), models.Index(fields=['ip_address'], name='core_websit_ip_addr_e400a7_idx'), models.Index(fields=['page_type'], name='core_websit_page_ty_7bdf1c_idx'), models.Index(fields=['device_type'], name='core_websit_device__36a1bc_idx'), models.Index(fields=['supplier'], name='core_websit_supplie_fea355_idx'), models.Index(fields=['user'], name='core_websit_user_id_a7d938_idx')],
            },
        ),
    ]
