# Generated by Django 6.0.1 on 2026-02-28 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_website_statistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='managing_users',
            field=models.ManyToManyField(blank=True, related_name='managed_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمين المدراء'),
        ),
    ]
