# Generated by Django 6.0.1 on 2026-03-02 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_supplier_managing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInquiryClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='معرف الجلسة')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الضغط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_inquiry_clicks', to='core.product', verbose_name='المنتج')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_inquiry_clicks', to='core.supplier', verbose_name='المتجر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_inquiry_clicks', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نقرة استفسار واتساب',
                'verbose_name_plural': 'نقرات استفسار واتساب',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
