# Generated by Django 6.0.1 on 2026-03-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_copy_store_id_to_subdomain'),
        ('core', '0081_whatsappinquiryclick'),
    ]

    operations = [
    ]
