# Generated by Django 6.0.1 on 2026-03-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_merge_20260311_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='footer_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف التذييل (Footer)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط انستقرام'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تيك توك'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تويتر'),
        ),
    ]
