# Generated by Django 6.0.3 on 2026-03-21 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_supplier_facebook_url_supplier_footer_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='enable_delivery_drivers',
            field=models.BooleanField(default=False, verbose_name='تفعيل نظام سائقي التوصيل'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='requires_driver_assignment',
            field=models.BooleanField(default=False, verbose_name='يتطلب تعيين سائق توصيل'),
        ),
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_drivers', to='core.supplier', verbose_name='المورد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_driver_profiles', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'سائق توصيل',
                'verbose_name_plural': 'سائقو التوصيل',
                'unique_together': {('user', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='core.deliverydriver', verbose_name='سائق التوصيل'),
        ),
    ]
