# Generated by Django 6.0.3 on 2026-03-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_supplier_enable_delivery_drivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.deliverydriver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'موقع السائق',
                'verbose_name_plural': 'مواقع السائقين',
                'ordering': ['-timestamp'],
            },
        ),
    ]
