# Generated by Django 6.0.1 on 2026-04-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_driverlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السمة (مثل: المقاس أو اللون)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='القيمة (مثل: XL أو أحمر)')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تعديل السعر (اختياري)')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.productattribute')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='core.productattributeoption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='core.productattributeoption'),
        ),
    ]
