# Generated by Django 6.0.1 on 2026-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_productattribute_productattributeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر العرض وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأساسي وقت الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_modifier_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مجموع إضافات الخيارات'),
        ),
    ]
