# Generated by Django 6.0.1 on 2026-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_order_delivery_fee_orderitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر العرض عند الإضافة'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأساسي عند الإضافة'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_modifier_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مجموع إضافات الخيارات'),
        ),
    ]
