# Generated by Django 6.0.1 on 2026-04-02 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_cartitem_discount_price_cartitem_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدورة')),
                ('slug', models.SlugField(unique=True, verbose_name='رابط الدورة')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='academy/thumbnails/', verbose_name='صورة الدورة')),
                ('estimated_duration', models.CharField(max_length=50, verbose_name='الوقت المقدر (مثلاً: 2 ساعة)')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='المستوى')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دورة تدريبية',
                'verbose_name_plural': 'الدورات التدريبية',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الفصل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدرس')),
                ('content', models.TextField(verbose_name='محتوى الدرس (Markdown)')),
                ('video_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف فيديو يوتيوب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.chapter', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقدم الدرس',
                'verbose_name_plural': 'تقدم الدروس',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
