# Generated by Django 6.0.3 on 2026-04-14 19:34

from django.db import migrations

def patch_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('core', 'Profile')
    Supplier = apps.get_model('core', 'Supplier')

    used_phones = set()

    # 1. Ensure all users have a Profile
    for user in User.objects.all():
        if not Profile.objects.filter(user=user).exists():
            Profile.objects.create(user=user, user_type='customer')

    # 2. Iterate through Profiles and apply user_type and phone numbers
    for profile in Profile.objects.all():
        user = profile.user
        candidate_phone = None

        # Check if user is associated with a Supplier
        # Using filter to avoid RelatedObjectDoesNotExist
        supplier = Supplier.objects.filter(user=user).first()
        if supplier:
            profile.user_type = 'supplier'
            if supplier.phone:
                candidate_phone = str(supplier.phone).strip()

        if not candidate_phone:
            # Check if user is a member of managing_users in any supplier
            managed = Supplier.objects.filter(managing_users=user).first()
            if managed:
                profile.user_type = 'supplier'

        # Apply phone uniqueness logic
        if candidate_phone:
            if candidate_phone in used_phones:
                profile.phone_number = None
            else:
                profile.phone_number = candidate_phone
                used_phones.add(candidate_phone)
        else:
            profile.phone_number = None

        profile.save(update_fields=['user_type', 'phone_number'])

def reverse_patch(apps, schema_editor):
    pass  # We don't want to revert user types or delete profiles automatically

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_profile_add_phone'),
    ]

    operations = [
        migrations.RunPython(patch_users, reverse_patch),
    ]

