# Generated by Django 6.0.1 on 2026-04-14 20:45

import core.db.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_patch_legacy_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد بالجملة')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد جملة',
                'verbose_name_plural': 'موردين الجملة',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الشراء'),
        ),
        migrations.CreateModel(
            name='WholesaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء (للمتاجر)')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع المقترح')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='المخزون المتاح')),
                ('image', models.ImageField(upload_to=core.db.utils.upload_to_path, verbose_name='صورة المنتج الرئيسية')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.db.utils.upload_to_path, verbose_name='فيديو المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_products', to='core.productcategory', verbose_name='الفئة')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_products', to='core.wholesalesupplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'منتج جملة',
                'verbose_name_plural': 'منتجات الجملة',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_products', to='core.wholesaleproduct', verbose_name='المصدر (الجملة)'),
        ),
        migrations.CreateModel(
            name='WholesaleProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.db.utils.upload_to_path, verbose_name='صورة إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.wholesaleproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج جملة',
                'verbose_name_plural': 'صور منتجات الجملة',
            },
        ),
    ]
