# Generated by Django 6.0.1 on 2026-04-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_wholesalesupplier_product_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='can_buy_wholesale',
            field=models.BooleanField(default=False, verbose_name='السماح بشراء الجملة (Sourcing)'),
        ),
    ]
