# Generated by Django 6.0.1 on 2026-04-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_paymentmethod_supplierpaymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.supplierpaymentmethod', verbose_name='وسيلة الدفع المختارة'),
        ),
    ]
