# Generated by Django 6.0.1 on 2026-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_order_selected_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='navbar_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
