# Generated by Django 6.0.3 on 2026-04-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_supplier_navbar_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
