# Generated by Django 6.0.1 on 2026-04-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_paymenttransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='text_color',
            new_name='footer_text_color',
        ),
    ]
