# Generated by Django 6.0.1 on 2026-08-16 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_rename_text_color_supplier_footer_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasadPayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='معرف العملية (ID)')),
                ('transaction_uuid', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='معرف UUID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency', models.CharField(default='YER', max_length=10, verbose_name='العملة')),
                ('service', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز الوسيلة (Service)')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الوسيلة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع بنجاح'), ('failed', 'فشلت العملية'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز الحالة')),
                ('status_display', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف الحالة')),
                ('checkout_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الدفع المستضاف')),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف العميل')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم العميل')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='استجابة البوابة')),
                ('raw_webhook_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الإشعار')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasadpay_transaction', to='core.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasadpay_transactions', to='core.supplier')),
            ],
            options={
                'verbose_name': 'عملية دفع حصاد باي',
                'verbose_name_plural': 'عمليات دفع حصاد باي',
            },
        ),
        migrations.CreateModel(
            name='SupplierHasadPayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل بوابة حصاد باي')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API (API Key)')),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف القناة (Entity ID)')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='المفتاح السري للـ Webhook (Webhook Secret)')),
                ('environment', models.CharField(choices=[('production', 'بيئة الإنتاج الحية (Production)'), ('sandbox', 'بيئة الاختبار التجريبية (Sandbox/Test)')], default='production', max_length=20, verbose_name='البيئة')),
                ('custom_base_url', models.URLField(blank=True, null=True, verbose_name='رابط بوابة مخصص (اختياري)')),
                ('display_name', models.CharField(default='حصاد باي - الدفع الإلكتروني المباشر', max_length=100, verbose_name='الاسم الظاهر للعملاء')),
                ('auto_confirm_order', models.BooleanField(default=True, verbose_name='تأكيد الطلب تلقائياً عند نجاح الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasadpay_config', to='core.supplier')),
            ],
            options={
                'verbose_name': 'إعدادات حصاد باي للتاجر',
                'verbose_name_plural': 'إعدادات حصاد باي للتجار',
            },
        ),
    ]
