# Generated by Django 6.0.1 on 2026-08-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_hasadpaytransaction_supplierhasadpayconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods/'),
        ),
    ]
