# Generated by Django 6.0.1 on 2026-04-20 17:25

import core.db.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0099_paymenttransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='المدة بالأيام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('max_products', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للمنتجات')),
                ('max_categories', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للفئات')),
                ('can_use_custom_subdomain', models.BooleanField(default=False, verbose_name='نطاق فرعي مخصص')),
                ('can_buy_wholesale', models.BooleanField(default=False, verbose_name='شراء بالجملة')),
                ('enable_delivery_drivers', models.BooleanField(default=False, verbose_name='نظام السائقين')),
                ('show_system_logo', models.BooleanField(default=True, verbose_name='عرض شعار المنصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='طريقة الدفع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.db.utils.upload_to_path, verbose_name='الشعار')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('pending', 'قيد الانتظار'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('is_trial', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_data', models.JSONField(blank=True, default=dict, help_text='Values for dynamic fields')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to=core.db.utils.upload_to_path, verbose_name='إيصال الدفع')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('pic', 'صورة/مرفق')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='نص توضيحي')),
                ('validation_regex', models.CharField(blank=True, max_length=200, null=True, verbose_name='التحقق (Regex)')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='subscriptions.subscriptionpaymentmethod')),
            ],
        ),
    ]
