# Generated by Django 6.0.1 on 2026-04-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='د.ك', max_length=10, verbose_name='العملة'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='الميزة')),
                ('is_included', models.BooleanField(default=True, verbose_name='مضمنة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.plan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'ميزة الباقة',
                'verbose_name_plural': 'ميزات الباقات',
                'ordering': ['order'],
            },
        ),
    ]
