# Generated by Django 6.0.1 on 2026-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_publicannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='publicannouncement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/broadcasts/'),
        ),
    ]
